security:
    providers:
        login:
            entity:
                class: App\Entity\User
                property: email 
    access_control:
        - { path: ^/feed, roles: [ROLE_USER, ROLE_ADMIN] }
        - { path: ^/mutuals, roles: [ROLE_USER, ROLE_ADMIN] }
        - { path: ^/newPost, roles: [ROLE_USER, ROLE_ADMIN] }
        - { path: ^/newComment, roles: [ROLE_USER, ROLE_ADMIN] }
        - { path: ^/notifications, roles: [ROLE_USER, ROLE_ADMIN] }
        - { path: ^/profile, roles: [ROLE_USER, ROLE_ADMIN] }
        - { path: ^/profileEdit, roles: [ROLE_USER, ROLE_ADMIN] }
        - { path: ^/admin, roles: [ROLE_ADMIN] }
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
            algorithm: auto
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: login
            form_login:
                login_path: ctrl_login
                check_path: ctrl_login
                default_target_path: feed 
            logout:
                path:   ctrl_logout
                target: ctrl_login    
