security:
    providers:
        login:
            entity:
                class: App\Entity\User
                property: username
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
            algorithm: auto
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: login
            form_login:
                login_path: ctrl_login
                check_path: ctrl_login
                default_target_path: categorias
            logout:
                path:   ctrl_logout
                target: ctrl_login    
